# Generated by Django 3.2.25 on 2024-07-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('short_description', models.CharField(max_length=500, verbose_name='Short Overview')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(default='blogs/default.png', upload_to='blogs/', verbose_name='Blog Image')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
